.TH dbeacon "1" "User Manuals"
.SH NAME
dbeacon \- Distributed IPv4/IPv6 multicast beacon
.SH SYNOPSYS
\fBdbeacon\fR \fB-a \fIMAIL\fR \fB-b \fIBEACON_ADDR\fR[/\fIPORT\fR] [\fB-i\fR \fIINTFNAME\fR] [\fB-n\fR \fINAME\fR] [\fB-r\fR \fIREDIST_ADDR\fR[/\fIPORT\fR]] [\fB-S\fR [\fIGROUP_ADDR\fR[/\fIPORT\fR]] [\fB-s\fR \fIADDR\fR] [\fB-d\fR [\fIFILE\fR]] [\fB-I\fR \fINUMBER\fR] [\fB-l\fR \fILOCAL_ADDR\fR[/\fIPORT\fR] [\fB-W\fR \fItype$url\fR] [\fB-L \fIprogram\fR] [\fB-4\fR][\fB-6\fR][\fB-v\fR][\fB-U\fR][\fB-V\fR]
.SH DESCRIPTION
\fBdbeacon\fR is a network level management tool aiming at getting various statistics about multicast connectivity. Its first usage is to check out if you can send/receive toward/from an IPv4/IPv6 multicast network. Its second usage is to gather various statistics by using a known multicast ASM group, for example TTL between each multicast peers, loss or jitter figures. Theses statistics are kept internally but can be dumped periodically in a file in xml format for latter processing. Statistics gathering is completetly distributed and rely on the powerful nature of ASM. No server is required, but maybe a http server for accessing the statistics and build an adjacency matrix of the peers.
.SH OPTIONS
.TP
\fB-a\fR \fIMAIL\fR
Administrative contact. This is an e-mail used for join you, for example to
notify you that something is wrong is your multicast connectivity
.TP
\fB-b\fR \fIBEACON_ADDR\fR/\fIPORT\fR
This is the IPv4/IPv6 address of the ASM group used by dbeacon to gather statistics. It can be specified as a DNS name too.
.TP
\fB-n\fR \fINAME\fR
The name identifying you on the dbeacon session. If not specified, dbeacon will use the hostname of the running machine.
.TP
\fB-r\fR \fIREDIST_ADDR\fR/\fIPORT\fR
.TP
\fB-S\fR \fIGROUP_ADDR\fR/\fIPORT\fR
.TP
\fB-s\fR \fIADDR\fR
.TP
\fB-d\fR \fIFILE\fR
.TP
\fB-I\fR \fINUMBER\fR
.TP
\fB-l\fR \fILOCAL_ADDR\fR/\fIPORT\fR
.TP
\fB-W\fR \fItype$url\fR
.TP
\fB-L\fR \fIprogram\fR
.TP
\fB-4\fR
.TP
\fB-6\fR
.TP
\fB-v\fR
.TP
\fB-U\fR
.TP
\fB-V\fR
.SH BUGS
Please report them to ...
.SH HISTORY
\fBdbeacon\fR is a join work from Hugo Santos, Sebastien Chaumonet and Mickael Hoerdt. It has been
done in the early days of the m6bone, when nobodies know if it was ASM or SSM at the interdomain level ;).
